<?xml version="1.0" encoding="utf-8" ?>
<xsl:stylesheet version="1.0"
    xmlns="http://schemas.microsoft.com/wix/2006/wi"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:wix="http://schemas.microsoft.com/wix/2006/wi">

  <xsl:output method="xml" indent="yes" />
  <xsl:strip-space elements="*"/>

  <xsl:variable name="platform">TEST</xsl:variable>
  <xsl:variable name="javaRuntimeSubfoldername">TEST</xsl:variable>

  <xsl:template match="wix:Wix">
    <Wix>
      <xsl:comment>*********************************************************************************************************************************************************************</xsl:comment>
      <xsl:comment>*********************************************************************************************************************************************************************</xsl:comment>
      <xsl:comment>*********************************************************************************************************************************************************************</xsl:comment>
      <xsl:comment>This code is AUTO-GENERATED by a combination of HEAT.EXE and the JDK.HeatTx.<xsl:value-of select="$platform" />.xslt</xsl:comment>
      <xsl:comment>*********************************************************************************************************************************************************************</xsl:comment>
      <xsl:comment>*********************************************************************************************************************************************************************</xsl:comment>
      <xsl:comment>*********************************************************************************************************************************************************************</xsl:comment>
      
      <xsl:processing-instruction name="define">JDK="$(var.Root)JDK/server-jre-windows-<xsl:value-of select="$platform" />/<xsl:value-of select="$javaRuntimeSubfoldername" />/"</xsl:processing-instruction>
      <xsl:apply-templates select="wix:Fragment" />
    </Wix>
  </xsl:template>

  <xsl:template match="wix:Wix/wix:Fragment" name="Fragments">
    <Fragment>
      <xsl:apply-templates />
    </Fragment>
  </xsl:template>

  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="node()|@*" name="all">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>